---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`horas_fermentacion > 10 and < 14`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`horas_fermentacion > 14 and < 10`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`horas_fermentacion > 10 and horas_fermentacion < 14`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`horas_fermentacion > 14 and horas_fermentacion < 10`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`horas_fermentacion > 10 or horas_fermentacion < 14`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`horas_fermentacion > 14 or horas_fermentacion < 10`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`14 < horas_fermentacion > 10`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`14 < horas_fermentacion < 10`"
  checked: false
name: New exercise
