---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`funcion_misteriosa(10, 1) devuelve True`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`funcion_misteriosa(10, 1) devuelve False`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`funcion_misteriosa(1, 1) devuelve True`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`funcion_misteriosa(1, 1) devuelve False`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`funcion_misteriosa(1, 0) devuelve True`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`funcion_misteriosa(1, 0) devuelve False`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`funcion_misteriosa("1", 0) produce un error`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`funcion_misteriosa(1, -1) produce un error`"
  checked: false
name: Un bis
