---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Faltan paréntesis  en torno a `(permiso_especial and registro)`
  checked: false
- value: Faltan paréntesis en torno a `(edad > 20 or permiso_especial)`
  checked: true
- value: Faltan paréntesis en torno a toda la expresión retornada
  checked: false
- value: Faltan paréntesis en otro lugar
  checked: false
- value: La función tiene más de tres parámetros (el máximo número permitido por Python)
  checked: false
- value: Hay un error de sintaxis
  checked: false
- value: La comparación `registro == True` es redundante, se debería escribir directamente
    `registro`
  checked: true
- value: La comparación `monto_infracciones == 0` es incorrecta, se debería escribir
    `monto_infracciones > 0`
  checked: false
name: Se alquila
