---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`str.startswith(password, "_") or str.startswith(password, "-") or str.startswith(password,
    ".")`'
  checked: false
- value: '`str.startswith(password, "_") or str.startswith("-") or str.startswith(".")`'
  checked: false
- value: '`password in "_" or password in "-" or password in "."`'
  checked: false
- value: '`password in "_" and "-" and "."`'
  checked: false
- value: '`"_" in password or "-" in password or "." in password`'
  checked: true
- value: '`"_" in password and "-" in password and "." in password`'
  checked: false
- value: '`"_" == password and "-" == password and "." == password`'
  checked: false
- value: '`"_" == password or "-" == password or "." == password`'
  checked: false
- value: '`"_" or "-" or "." in password`'
  checked: false
- value: '`"_" and "-" and "." in password`'
  checked: false
name: Máxima seguridad
