---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Faltan paréntesis  en torno a `(permiso_especial and registro)`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Faltan paréntesis en torno a `(edad > 20 or permiso_especial)`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Faltan paréntesis en torno a toda la expresión retornada
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Faltan paréntesis en otro lugar
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La función tiene más de tres parámetros (el máximo número permitido por Python)
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Hay un error de sintaxis
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La comparación `registro == True` es redundante, se debería escribir directamente
    `registro`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La comparación `monto_infracciones == 0` es incorrecta, se debería escribir
    `monto_infracciones > 0`
  checked: false
name: Nuevo ejercicio
